---
services:

  php:
    build:
      context: ./build
      dockerfile: php.dockerfile
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      TZ: "${TZ:-Europe/Berlin}"
      PHP_IDE_CONFIG: "serverName=docker"
      WEBMAIL_PORT: "${WEBMAIL_PORT:-8025}"
      PHPMYADMIN_PORT: "${PHPMYADMIN_PORT:-8081}"
    volumes:
      - ./build/index.php:/application/index.php
      - ./php:/application/php
    restart: unless-stopped
    networks:
      - dhbw
    depends_on:
      db:
        condition: service_healthy


  web:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${HTTP_PORT:-8080}:80"
      - "127.0.0.1:${HTTPS_PORT:-8443}:443"
    volumes:
      - ./build/nginx:/etc/nginx/conf.d
      - ./build/index.php:/application/index.php:ro
      - ./php:/application/php
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      dhbw:
        aliases:
          - dhbw.test
    depends_on:
      - php


  db:
    image: mariadb:11.8
    # increaase max package size to 64MB and
    # make windows dumps with uppercase tablesnames compatible with other OSes
    command: --max_allowed_packet=67108864 --lower_case_table_names=1
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DB_PORT:-8306}:3306"
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_AUTO_UPGRADE=1
      - TZ=${TZ:-Europe/Berlin}
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./log/mariadb:/var/log/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - dhbw


  mail:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${WEBMAIL_PORT:-8025}:8025"
      - "127.0.0.1:${SMTP_PORT:-1025}:1025"
    networks:
      - dhbw


  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PHPMYADMIN_PORT:-8081}:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      # allow importing bigger SQL dumps
      - UPLOAD_LIMIT=64M
    networks:
      - dhbw
    depends_on:
      db:
        condition: service_healthy


networks:
  dhbw:
    name: "${COMPOSE_PROJECT_NAME:-dhbw}"
    external: false


# vim: syntax=yaml ts=2 sw=2 et sr softtabstop=2 autoindent
